export const STR = {
  title: "LUMA BALL LEAGUE",
  subtitle: "Eclipse Season — Astral Veil vs Obsidian Veil",
  tagline: "Light does not follow legends. Legends create light.",
  startMatch: "Start Match",
  selectLane: "Choose a lane to charge or shoot",
  charge: "CHARGE",
  shoot: "SHOOT",
  yourTurn: "Your move, Captain",
  resolving: "Resolving round...",
  goalScored: "GOAL! Astral Veil scores!",
  goalBlocked: "BLOCKED by Obsidian Veil!",
  aiGoal: "Obsidian Veil breaks through!",
  aiBlocked: "Astral Veil holds the line!",
  charged: "Charge built",
  needCharge: "Need at least 1 charge to shoot",
  win: "ECLIPSE CUP: ASTRAL VEIL VICTORY",
  lose: "ECLIPSE CUP: OBSIDIAN VEIL VICTORY",
  playAgain: "Play Again",
  astralScore: "Astral Veil",
  obsidianScore: "Obsidian Veil",
  round: "Round",
  charge0: "No charge",
  charge1: "Charge I",
  charge2: "Charge II",
  charge3: "Charge III — Breakthrough!",
  aiDefending: "Obsidian Veil sets their defense...",
  howTo: "Tap a lane's CHARGE to build power (max III). Tap SHOOT (needs Charge I+) to attempt a goal. Obsidian Veil will try to defend a lane each round — Charge III breaks through any block!",
  close: "Got it",
  muteOn: "Sound: On",
  muteOff: "Sound: Off",
};
